services:
  query-api:
    image: robotech/query-api:0.0.0
    build:
      context: .
      dockerfile: gateway/query-api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./config/query-api.toml
        target: /etc/robotech/query-api.toml
        read_only: true
        bind:
          create_host_path: false
    read_only: true
    stop_grace_period: 15s
    restart: "no"
