[package]
name = "query-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
chrono.workspace = true
clap.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

service-runtime.workspace = true
trade-log.workspace = true
shared-types.workspace = true
reqwest.workspace = true
serde_json.workspace = true

[dev-dependencies]

[[test]]
name = "query_api"
path = "../../tests/integration-tests/query_api.rs"
