[package]
name = "trade-parser-publisher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
trade-log.workspace = true
trade-log-adapters.workspace = true
shared-types.workspace = true
service-runtime.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
clap.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

reqwest.workspace = true
